<a href="https://colab.research.google.com/github/akhmadhidayat/UAS/blob/main/No_1_b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Dataset
jeniskelamin =['laki','laki', 'perempuan', 'perempuan', 'laki', 'laki', 'perempuan', 'perempuan', 'laki', 'perempuan']
biaya =['murah', 'murah', 'murah','murah','murah', 'standar', 'standar', 'mahal', 'mahal', 'mahal']
incomelevel =['rendah',  'sedang', 'sedang', 'rendah','sedang', 'sedang', 'sedang', 'tinggi', 'sedang', 'tinggi']
modeltrans =['bus',  'bus', 'kereta', 'bus','bus', 'kereta', 'kereta', 'mobil', 'mobil', 'mobil']

tujuan =['no', 'yes','yes','no', 'yes', 'no', 'yes', 'yes', 'no', 'no']

In [2]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
#Convert label string ke numbers
jeniskelamin_encoded=le.fit_transform(jeniskelamin)
print (jeniskelamin_encoded)

[0 0 1 1 0 0 1 1 0 1]


In [3]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
label = preprocessing.LabelEncoder()
#Convert label string ke numbers
biaya_encoded=label.fit_transform(biaya)
print (biaya_encoded) 

incomelevel_encoded=label.fit_transform(incomelevel)
print (incomelevel_encoded)

modeltrans_encoded=label.fit_transform(modeltrans)
print (modeltrans_encoded)

tujuan_encoded=label.fit_transform(tujuan)
print (tujuan_encoded)

[1 1 1 1 1 2 2 0 0 0]
[0 1 1 0 1 1 1 2 1 2]
[0 0 1 0 0 1 1 2 2 2]
[0 1 1 0 1 0 1 1 0 0]


In [4]:
print ("jeniskelamin            :",jeniskelamin_encoded)
print ("biaya                   :",biaya_encoded)
print ("incomelevel             :",incomelevel_encoded)
print ("modeltrans              :",modeltrans_encoded)
print ("tujuan                  :",tujuan_encoded)

jeniskelamin            : [0 0 1 1 0 0 1 1 0 1]
biaya                   : [1 1 1 1 1 2 2 0 0 0]
incomelevel             : [0 1 1 0 1 1 1 2 1 2]
modeltrans              : [0 0 1 0 0 1 1 2 2 2]
tujuan                  : [0 1 1 0 1 0 1 1 0 0]


In [5]:
#Combining fitur-fitur yang ada
features=zip(jeniskelamin_encoded,biaya_encoded,incomelevel_encoded,modeltrans_encoded)
features=list(features)
print (tuple(features))

((0, 1, 0, 0), (0, 1, 1, 0), (1, 1, 1, 1), (1, 1, 0, 0), (0, 1, 1, 0), (0, 2, 1, 1), (1, 2, 1, 1), (1, 0, 2, 2), (0, 0, 1, 2), (1, 0, 2, 2))


In [6]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Panggil Gaussian Classifier
model = GaussianNB()

#Train model untuk data training
model.fit(features,tujuan)
#Model.fit(features,label.reshape(-1,1))

#Peridiction Output
predicted = model.predict([[1,2,0,0]]) #1 : perempuan, 1: biaya, 2: incomelevel , 0 : modeltrans, 0 :
print ("Hasil Perdiksi:", predicted)

Hasil Perdiksi: ['no']
